### ISSUE TITLE
Switch off interactive questions

### ISSUE THREAD

**Issue by kkalass** [joblift/maven-cascade-release#1]
I often loose some time because cascade-release does some work and then asks some questions - but I cannot watch the process all the time because the work it does takes so long. So sometimes it takes hours until I notice the question.

In order to be able to use this tool in a "fire and forget" way it would be really helpful if I could provide my answers to the questions beforehand on the commandline. For example:

`--continue-interrupted-release=false` and `--always-approve-after-verify=true`

**Comment by galan** [comment]
I would like to close this feature, since the current version does only check the repositories once now, which reduces the time for an interrupted release dramatically. Any objections? @kkalass

**Comment by kkalass** [comment]
Ok, I will reopen it if it bothers me again
